version: 0.2

phases: 
  install:
    commands:
      - echo Installing Node 16..
      - curl -fsSL https://deb.nodesource.com/setup_16.x | bash -
      - apt install -y nodejs
      - echo Installing Yarn
      - npm install -g yarn
  pre_build:
    commands:
      - echo Installing Project Dependencies
      - yarn
  build:
    commands:
      - echo Building...
      - yarn build
artifacts:
    files:
      - "**/*"
    discard-paths: no
    base-directory: build